name: buddyapp
description: This is YoBuddy Mobile App

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  async_loader: ^0.1.1
  json_annotation: ^0.2.2
  http: "^0.11.3+16"
  sqflite: "^0.8.9"
  path_provider: "^0.4.0"
  intl: "^0.15.6"
  shared_preferences: "^0.4.1"
  flutter_staggered_grid_view: "^0.1.4"
  flutter_radial_menu: "^0.0.1"
  sticky_headers: "^0.1.4"
  html2md: "^0.1.5"
  flutter_markdown: "^0.1.5"
  flutter_advanced_networkimage: "^0.2.6"
  transparent_image: "^0.1.0"
  timeago: ^1.2.7
#  zefyr: ^0.1.2
  flutter_multiple_image_picker: ^0.0.1
  multi_image_picker: ^1.0.51
  dio: ^1.0.0

dev_dependencies:
  build_runner: ^0.7.6
  json_serializable: ^0.5.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ionicon
      fonts:
        - asset: assets/fonts/ionicons.ttf
    - family: didact
      fonts:
          - asset: assets/fonts/DidactGothic-Regular.ttf
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
